### ISSUE TITLE
issue while installing with npm

### ISSUE THREAD

**Issue by gilles747** [svrcekmichal/react-sketchpad#1]
Hi, 

I was interesting to test your work within a npm install. As such I did 
npm install --save  https://github.com/svrcekmichal/react-sketchpad

Because of the .npmignore the .src was not included, as then the import of Sketchpad did not work. 
Any reason why this src directory was not included ?

**Comment by svrcekmichal** [comment]
@gilles747 you can use `npm i -S react-sketchpad` to install it. Hope it helps.
