### ISSUE TITLE
The package is installed but cannot be found at runtime

### ISSUE THREAD

**Issue by luvemil** [svrcekmichal/react-sketchpad#3]
After installing with `npm install --save react-sketchpad` I can find the module correctly positioned in the node_modules directory but still when called with, for example
```
import { Sketchpad } from 'react-sketchpad';
```
`gulp` gives a `Error: Cannot find module 'react-sketchpad'`.

A simple solution is to do
```
import { Sketchpad } from '../node_modules/react-sketchpad/lib/index';
```

Maybe this is a problem of my version of nodejs/react/os/whatever. I will try to see if it can be fixed.

**Comment by svrcekmichal** [comment]
@luvemil Try to clear your `node_modules` folder and then install it. Fixed the issue for me most of the time, it is not related to this package.
